name: 🐛 Bug Report
description: Report something that isn't working correctly in the system
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        
        Found something that's not working right? Help us fix it by providing clear details about what's happening.
        
  - type: textarea
    id: what-happened
    attributes:
      label: What went wrong?
      description: Describe what happened that shouldn't have happened
      placeholder: e.g., "When I try to sign up students for Chess Club, I get an error message"
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: What should have happened instead?
      description: Describe what you expected to happen
      placeholder: e.g., "The student should be added to Chess Club and I should see a success message"
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: How can someone else see this problem?
      description: List the steps to reproduce the issue
      placeholder: |
        1. Go to the website
        2. Log in as a teacher
        3. Try to sign up a student for an activity
        4. See error message
    validations:
      required: true
      
  - type: dropdown
    id: affected-area
    attributes:
      label: What part of the system has the problem?
      description: Select the area where you're seeing the issue
      options:
        - Student signup/registration
        - Teacher login
        - Activity display/listing
        - Website loading/performance
        - Student enrollment management
        - Activity scheduling display
        - Search or filtering
        - Other (explain below)
    validations:
      required: true
      
  - type: dropdown
    id: how-often
    attributes:
      label: How often does this happen?
      description: Select how frequently you see this problem
      options:
        - Every time I try
        - Most of the time
        - Sometimes
        - Rarely
        - Only happened once
    validations:
      required: true
      
  - type: input
    id: error-message
    attributes:
      label: Error Message (if any)
      description: If you see an error message, type it exactly here
      placeholder: e.g., "Failed to update activity" or "Authentication required"
    validations:
      required: false
      
  - type: dropdown
    id: browser
    attributes:
      label: What web browser are you using?
      description: Select your browser
      options:
        - Google Chrome
        - Mozilla Firefox
        - Safari
        - Microsoft Edge
        - Other
        - Don't know
    validations:
      required: false
      
  - type: input
    id: teacher-affected
    attributes:
      label: Which teacher account is affected?
      description: If this is related to a specific teacher login
      placeholder: e.g., "Ms. Rodriguez", "Mr. Chen"
    validations:
      required: false
      
  - type: textarea
    id: additional-info
    attributes:
      label: Any other helpful information?
      description: Anything else that might help us understand and fix the problem
      placeholder: e.g., "This started happening yesterday", "Only affects certain activities"
    validations:
      required: false
      
  - type: markdown
    attributes:
      value: |
        ## Acceptance Criteria
        
        When this bug is fixed, the following should be true:
        - [ ] The problem no longer occurs when following the reproduction steps
        - [ ] Normal functionality is restored for the affected feature
        - [ ] No new problems are introduced by the fix
        - [ ] The fix works across different browsers and user accounts
        - [ ] Similar edge cases are also addressed
        
        ## Implementation Hints
        
        **For the Copilot coding agent:**
        - First reproduce the issue by following the steps provided
        - Check browser developer console for JavaScript errors
        - Review server logs for backend errors
        - Look for common issues in the affected code area:
          - Authentication problems in `src/backend/routers/auth.py`
          - Activity management issues in `src/backend/routers/activities.py`
          - Database connection/query issues in `src/backend/database.py`
          - Frontend JavaScript errors in `src/static/app.js`
        - Test the fix thoroughly before marking as complete
        - Consider edge cases and error handling
        
        ## Context
        
        This is for the Mergington High School activity management system. The system should work reliably for teachers and students to manage extracurricular activities. Bugs affect the daily operations of the school.