blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/JonathanJonsson-dev/skills-expand-your-team-with-copilot/discussions
    about: Ask questions about using the activity management system
  - name: 📚 Documentation
    url: https://github.com/JonathanJonsson-dev/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Read the development guide and system documentation